version: "3.8"

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./mail-data:/var/mail
      - ./mail-state:/var/mail-state
      - ./mail-logs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - ./ssl/:/etc/letsencrypt/live/
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - SSL_TYPE=letsencrypt
      - TZ=America/Sao_Paulo
      - MAIL_DOMAIN=${DOMAINNAME}
      - MAIL_HOSTNAME=${HOSTNAME}
      - PERMIT_DOCKER=host
      - ONE_DIR=1
      - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=1
      - POSTFIX_DAGENT=lmtp:dovecot:24
      - REPORT_RECIPIENT=1
      - DOVECOT_MAILBOX_FORMAT=maildir
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: unless-stopped
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "25"]
      interval: 30s
      timeout: 10s
      retries: 5
    dns:
      - 8.8.8.8
      - 1.1.1.1 