version: "3.8"

services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.tonet.dev
    domainname: tonet.dev
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./data:/var/mail
      - ./state:/var/mail-state
      - ./logs:/var/log/mail
      - ./config:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - SSL_TYPE=letsencrypt
      - TZ=America/Sao_Paulo
      - MAIL_DOMAIN=tonet.dev
      - MAIL_HOSTNAME=mail.tonet.dev
      - PERMIT_DOCKER=network
      - ONE_DIR=1
      - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=1
      - POSTFIX_DAGENT=lmtp:dovecot:24
      - REPORT_RECIPIENT=1
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "25"]
      interval: 30s
      timeout: 10s
      retries: 5 