version: "3.8"

services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    hostname: mail.tonet.dev
    domainname: tonet.dev
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - data:/var/mail
      - state:/var/mail-state
      - logs:/var/log/mail
      - config:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
      - MAIL_DOMAIN=tonet.dev
      - MAIL_HOSTNAME=mail.tonet.dev
      - HOSTNAME=mail.tonet.dev
      - DOMAINNAME=tonet.dev
      - DMS_HOSTNAME=mail.tonet.dev
      - DMS_DOMAINNAME=tonet.dev
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
    networks:
      - easypanel

volumes:
  data:
    driver: local
  state:
    driver: local
  logs:
    driver: local
  config:
    driver: local

networks:
  easypanel:
    external: true 