services:
  mailserver:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - data:/var/mail
      - state:/var/mail-state
      - logs:/var/log/mail
      - config:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - SSL_TYPE=letsencrypt
      - TZ=America/Sao_Paulo
      - MAIL_DOMAIN=tonet.dev
      - MAIL_HOSTNAME=mail.tonet.dev
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

volumes:
  data:
  state:
  logs:
  config: 