version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    container_name: mailserver
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/tmp/docker-mailserver
      - maildata:/var/mail
      - maildata:/var/lib/dovecot
      - maildata:/etc/postfix
      - mail-state:/var/mail-state
      - mail-logs:/var/log/mail
      - mail-config:/tmp/docker-mailserver
      - ssl-certs:/etc/ssl/docker-mailserver
    environment:
      - SSL_TYPE
      - SSL_CERT_PATH
      - SSL_KEY_PATH
      - HOSTNAME
      - DOMAINNAME
      - MAIL_DOMAIN
      - MAIL_HOSTNAME
      - POSTMASTER_ADDRESS
      - TZ
      - ENABLE_SPAMASSASSIN
      - ENABLE_CLAMAV
      - ENABLE_FAIL2BAN
      - ENABLE_POSTGREY
      - ONE_DIR
      - PERMIT_DOCKER
      - ENABLE_POSTFIX_VIRTUAL_TRANSPORT
      - POSTFIX_DAGENT
      - REPORT_RECIPIENT
      - DOVECOT_MAILBOX_FORMAT
      - POSTFIX_INET_PROTOCOLS
      - DOVECOT_INET_PROTOCOLS
      - DMS_DEBUG
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: unless-stopped
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "25"]
      interval: 30s
      timeout: 10s
      retries: 5
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - easypanel

  roundcube:
    image: roundcube/roundcubemail:1.6.9-apache
    container_name: roundcube
    depends_on:
      - app
    env_file:
      - roundcube.env
    volumes:
      - roundcube_data:/var/www/html
    networks:
      - easypanel
    restart: unless-stopped

volumes:
  maildata:
    driver: local
  mail-state:
    driver: local
  mail-logs:
    driver: local
  mail-config:
    driver: local
  ssl-certs:
    driver: local
  roundcube_data:
    driver: local

networks:
  easypanel:
    external: true 