version: "3.8"

services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mail.tonet.dev
    hostname: mail.tonet.dev
    domainname: tonet.dev
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - data:/var/mail
      - state:/var/mail-state
      - logs:/var/log/mail
      - config:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
      - DMS_DEBUG=1
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - PERMIT_DOCKER=network
      - SSL_TYPE=letsencrypt
      - POSTMASTER_ADDRESS=luciano@tonet.dev
      - POSTFIX_INET_PROTOCOLS=ipv4
      - DOVECOT_INET_PROTOCOLS=ipv4
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
    networks:
      - easypanel
    extra_hosts:
      - "mail.tonet.dev:127.0.0.1"
      - "tonet.dev:127.0.0.1"

volumes:
  data:
    driver: local
  state:
    driver: local
  logs:
    driver: local
  config:
    driver: local

networks:
  easypanel:
    external: true 