version: "3.8"

services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: ${HOSTNAME}
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - data:/var/mail
      - state:/var/mail-state
      - logs:/var/log/mail
      - config:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
    environment:
      - HOSTNAME=${HOSTNAME}
      - DOMAINNAME=${DOMAINNAME}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MAIL_HOSTNAME=${MAIL_HOSTNAME}
      - POSTMASTER_ADDRESS=${POSTMASTER_ADDRESS}
      - SSL_TYPE=${SSL_TYPE}
      - TZ=${TZ}
      - DMS_DEBUG=${DMS_DEBUG}
      - ENABLE_SPAMASSASSIN=${ENABLE_SPAMASSASSIN}
      - ENABLE_CLAMAV=${ENABLE_CLAMAV}
      - ENABLE_FAIL2BAN=${ENABLE_FAIL2BAN}
      - ENABLE_POSTGREY=${ENABLE_POSTGREY}
      - ONE_DIR=${ONE_DIR}
      - PERMIT_DOCKER=${PERMIT_DOCKER}
      - POSTFIX_INET_PROTOCOLS=${POSTFIX_INET_PROTOCOLS}
      - DOVECOT_INET_PROTOCOLS=${DOVECOT_INET_PROTOCOLS}
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
    networks:
      - easypanel
    extra_hosts:
      - "${HOSTNAME}:127.0.0.1"
      - "${DOMAINNAME}:127.0.0.1"

volumes:
  data:
    driver: local
  state:
    driver: local
  logs:
    driver: local
  config:
    driver: local

networks:
  easypanel:
    external: true 