version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    container_name: mailserver
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    ports:
      - "25:25"    # SMTP (recebimento)
      - "465:465"  # SMTP sobre SSL (envio seguro legado)
      - "587:587"  # SMTP com STARTTLS (envio seguro moderno)
      - "993:993"  # IMAP sobre SSL (leitura segura)
    volumes:
      - maildata:/tmp/docker-mailserver
      - maildata:/var/mail
      - maildata:/var/lib/dovecot
      - maildata:/etc/postfix
      - mail-state:/var/mail-state
      - mail-logs:/var/log/mail
      - mail-config:/tmp/docker-mailserver
      - ssl-certs:/etc/ssl/docker-mailserver
    environment:
      - SSL_TYPE
      - SSL_CERT_PATH
      - SSL_KEY_PATH
      - HOSTNAME
      - DOMAINNAME
      - MAIL_DOMAIN
      - MAIL_HOSTNAME
      - POSTMASTER_ADDRESS
      - TZ
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - PERMIT_DOCKER=network
      - POSTFIX_INET_PROTOCOLS=ipv4
      - DOVECOT_INET_PROTOCOLS=ipv4
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: unless-stopped
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "25"]
      interval: 30s
      timeout: 10s
      retries: 5
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - easypanel

volumes:
  maildata:
    driver: local
  mail-state:
    driver: local
  mail-logs:
    driver: local
  mail-config:
    driver: local
  ssl-certs:
    driver: local

networks:
  easypanel:
    external: true