version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    container_name: mailserver
    hostname: ${HOSTNAME:-mail.tonet.dev}
    domainname: ${DOMAINNAME:-tonet.dev}
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ${DATA_PATH:-../mail-data}:/var/mail
      - ${STATE_PATH:-../mail-state}:/var/mail-state
      - ${LOGS_PATH:-../mail-logs}:/var/log/mail
      - ${CONFIG_PATH:-../config}:/tmp/docker-mailserver/
      - ${SSL_PATH:-../ssl}/${DOMAINNAME:-tonet.dev}:/tmp/ssl/${DOMAINNAME:-tonet.dev}:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/ssl/${DOMAINNAME:-tonet.dev}/fullchain.pem
      - SSL_KEY_PATH=/tmp/ssl/${DOMAINNAME:-tonet.dev}/privkey.pem
      - TZ=America/Sao_Paulo
      - MAIL_DOMAIN=${DOMAINNAME:-tonet.dev}
      - MAIL_HOSTNAME=${HOSTNAME:-mail.tonet.dev}
      - PERMIT_DOCKER=host
      - ONE_DIR=1
      - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=1
      - POSTFIX_DAGENT=lmtp:dovecot:24
      - REPORT_RECIPIENT=1
      - DOVECOT_MAILBOX_FORMAT=maildir
      - POSTFIX_INET_PROTOCOLS=ipv4
      - DOVECOT_INET_PROTOCOLS=ipv4
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: unless-stopped
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "25"]
      interval: 30s
      timeout: 10s
      retries: 5
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - easypanel

volumes:
  data:
    driver: local
  state:
    driver: local
  logs:
    driver: local
  config:
    driver: local

networks:
  easypanel:
    external: true 